[eksctl]
version="0.31.0"
tarpath="https://github.com/weaveworks/eksctl/releases/download/${version}/eksctl_${os}_${goarch}.tar.gz"

[jk]
version="0.3.2"
binarypath="https://github.com/jkcfg/jk/releases/download/${version}/jk-${goos}-${goarch}"

[footloose]
version="0.6.3"
binarypath="https://github.com/weaveworks/footloose/releases/download/${version}/footloose-${version}-${goos}-${arch}"
tarpath="https://github.com/weaveworks/footloose/releases/download/${version}/footloose-${version}-${goos}-${arch}.tar.gz"

[ignite]
version="0.8.0"
binarypath="https://github.com/weaveworks/ignite/releases/download/v${version}/ignite-${goarch}"

[controller]
version="v0.9.0-rc.1"

[hub]
version="2.14.2"
special_tarpath="https://github.com/github/hub/releases/download/v${version}/hub-${goos}-${goarch}-${version}.tgz;hub/hub-${goos}-${goarch}-${version}/bin"

[kubeseal]
version="0.11.0"
binarypath="https://github.com/bitnami-labs/sealed-secrets/releases/download/v${version}/kubeseal-${goos}-${goarch}"
